### PR TITLE
adding clone indirect buffer in popup

### PR DESCRIPTION
**Pull request by rhoit**

### CODE REVIEW

**Comment by mattfidler** [comment]
The function that works for me is:

```lisp

(defun tabbar-popup-clone-indirect-buffer ()
  "Tab-bar pop up clone indirect-buffer"
  (interactive)
  (let ((buffer (tabbar-tab-value tabbar-last-tab)))
    (with-current-buffer buffer
      (call-interactively 'clone-indirect-buffer))))

```

**Comment by mattfidler** [comment]
What is the point of clone indirect buffer.  I cannot find a use for it.

**Comment by rhoit** [comment]
@mattfidler to use multiple narrow mode!

**Comment by rhoit** [comment]
here is some use case!

http://demonastery.org/2013/04/emacs-narrow-to-region-indirect/

**Pull request merged**
